apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: "/mnt/data"  # Замените на путь, существующий на узле
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: worker
          operator: In
          values:
          - "apps"