apiVersion: v1
kind: Pod
metadata:
  name: pod-using-pvc-2
spec:
  serviceAccountName: ebs-access-sa   # Укажите здесь имя ServiceAccount
  nodeSelector:
    worker: apps                     # Указывает, что под должен запускаться на узле с меткой worker=apps
  containers:
  - name: my-container
    image: nginx
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    volumeMounts:
    - mountPath: "/data"
      name: pvc-storage
  volumes:
  - name: pvc-storage
    persistentVolumeClaim:
      claimName: example-pvc
