name: 'key-pair'

on:
  workflow_dispatch:   # Триггер для ручного запуска

jobs:
  terraform-kp-check:
    name: 'Terraform check'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACC_ID }}:role/GithubActionsRole
        aws-region: ap-southeast-1

    - name: Terraform Init
      run: terraform init
      working-directory: task-2/key-pair

    - name: Terraform Format
      run: terraform fmt
      working-directory: task-2/key-pair


  terraform-kp-plan:
    name: 'Terraform plan'
    runs-on: ubuntu-latest
    needs: terraform-kp-check

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Terraform Init
      run: terraform init
      working-directory: task-2/key-pair

    - name: Terraform Planning
      run: terraform plan -input=false
      working-directory: task-2/key-pair

  terraform-kp-apply:
    name: 'Terraform apply'
    runs-on: ubuntu-latest
    needs: terraform-kp-plan

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      working-directory: task-2/key-pair
